name: YardWatch
version: '${project.version}'
main: me.youhavetrouble.yardwatch.YardWatch
api-version: '1.13'
softdepend:
  - "WorldGuard"
  - "GriefPrevention"
  - "Towny"
authors:
  - "YouHaveTrouble"
description: "Implementation of YardWatchAPI for common protection plugins"
website: "https://youhavetrouble.me"
