name: '${project.artifactId}'
version: '${project.version}'
main: me.youhavetrouble.yardwatch.YardWatch
api-version: '1.16'
folia-supported: true
softdepend:
  - "WorldGuard"
  - "GriefPrevention"
  - "Towny"
authors:
  - "YouHaveTrouble"
description: '${project.description}'
website: '${project.url}'
